'use strict';
const fs = require('fs');
const path = require('path');

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    const buffer = await fs.promises.readFile(path.join(__dirname, '..', 'public', 'images', 'stock.jpg'));
    
    await queryInterface.bulkInsert('Courses', [
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Introduction to Business',
        description: 'Learn the basics of business management and gain insights into various aspects of the business world.',
        status: 'open',
        workload: 40,
        CategoryId: 1,
        start_date: '2023-07-30',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Web Development Fundamentals',
        description: 'Get started with web development and learn the fundamental concepts and technologies used in creating websites and web applications.',
        status: 'open',
        workload: 60,
        CategoryId: 2,
        start_date: '2023-07-31',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Digital Photography',
        description: 'Discover the art of digital photography and learn techniques to capture stunning images using digital cameras.',
        status: 'open',
        workload: 30,
        CategoryId: 3,
        start_date: '2023-08-01',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Spanish for Beginners',
        description: 'Start your journey in learning the Spanish language and explore the rich culture and traditions of Spanish-speaking countries.',
        status: 'open',
        workload: 45,
        CategoryId: 4,
        start_date: '2023-08-02',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Personal Branding Workshop',
        description: 'Learn how to effectively market yourself and create a strong personal brand that stands out in today\'s competitive world.',
        status: 'open',
        workload: 20,
        CategoryId: 5,
        start_date: '2023-08-03',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Yoga and Meditation',
        description: 'Improve your physical and mental well-being through the practice of yoga postures and meditation techniques.',
        status: 'open',
        workload: 60,
        CategoryId: 6,
        start_date: '2023-08-04',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Physics: Classical Mechanics',
        description: 'Explore the principles of classical mechanics and learn how objects move and interact under the influence of forces.',
        status: 'open',
        workload: 50,
        CategoryId: 7,
        start_date: '2023-08-05',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Introduction to Psychology',
        description: 'Gain a basic understanding of human behavior and the mind through an introduction to the field of psychology.',
        status: 'open',
        workload: 40,
        CategoryId: 8,
        start_date: '2023-08-06',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Financial Accounting Basics',
        description: 'Learn the fundamentals of financial accounting and develop skills to analyze and interpret financial statements.',
        status: 'open',
        workload: 35,
        CategoryId: 9,
        start_date: '2023-08-07',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Digital Marketing Strategies',
        description: 'Explore the world of digital marketing and learn strategies to effectively promote products and services online.',
        status: 'open',
        workload: 55,
        CategoryId: 10,
        start_date: '2023-08-08',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Leadership Principles',
        description: 'Develop essential leadership skills and learn effective strategies to lead teams and achieve organizational goals.',
        status: 'open',
        workload: 30,
        CategoryId: 11,
        start_date: '2023-08-09',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Creative Writing Workshop',
        description: 'Unleash your creativity and learn techniques to express yourself through various forms of creative writing.',
        status: 'open',
        workload: 25,
        CategoryId: 12,
        start_date: '2023-08-10',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Introduction to Civil Engineering',
        description: 'Get an introduction to the field of civil engineering and explore the design and construction of infrastructure projects.',
        status: 'open',
        workload: 40,
        CategoryId: 13,
        start_date: '2023-08-11',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Sustainable Development and Green Architecture',
        description: 'Learn about sustainable development practices and explore the principles of green architecture and design.',
        status: 'open',
        workload: 50,
        CategoryId: 14,
        start_date: '2023-08-12',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Environmental Science and Conservation',
        description: 'Discover the importance of environmental science and conservation efforts in preserving our planet for future generations.',
        status: 'open',
        workload: 35,
        CategoryId: 14,
        start_date: '2023-08-13',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Ancient History: From Mesopotamia to Rome',
        description: 'Journey back in time and explore the fascinating history of ancient civilizations from Mesopotamia to the Roman Empire.',
        status: 'open',
        workload: 55,
        CategoryId: 15,
        start_date: '2023-08-14',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Strategic Management',
        description: 'Learn the principles of strategic management and develop skills to formulate and implement business strategies.',
        status: 'open',
        workload: 40,
        CategoryId: 1,
        start_date: '2023-08-15',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Python for Data Science',
        description: 'Explore the powerful programming language Python and learn how to analyze and interpret data using data science techniques.',
        status: 'open',
        workload: 60,
        CategoryId: 2,
        start_date: '2023-08-16',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Graphic Design Essentials',
        description: 'Learn the fundamental principles of graphic design and develop skills to create visually appealing designs.',
        status: 'open',
        workload: 30,
        CategoryId: 3,
        start_date: '2023-08-17',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'French Language and Culture',
        description: 'Embark on a journey to learn the French language and explore the rich culture and traditions of French-speaking countries.',
        status: 'open',
        workload: 45,
        CategoryId: 4,
        start_date: '2023-08-18',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Time Management and Productivity Hacks',
        description: 'Master the art of time management and discover productivity hacks to optimize your personal and professional life.',
        status: 'open',
        workload: 20,
        CategoryId: 5,
        start_date: '2023-08-19',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Pilates for Beginners',
        description: 'Experience the benefits of Pilates and learn the foundational exercises to improve strength, flexibility, and posture.',
        status: 'open',
        workload: 60,
        CategoryId: 6,
        start_date: '2023-08-20',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Chemistry Fundamentals',
        description: 'Gain a solid understanding of the basic principles of chemistry and explore the properties and behavior of matter.',
        status: 'open',
        workload: 50,
        CategoryId: 7,
        start_date: '2023-08-21',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Philosophy: Introduction to Ethics',
        description: 'Delve into the field of philosophy and explore ethical theories, moral dilemmas, and the principles of ethical reasoning.',
        status: 'open',
        workload: 40,
        CategoryId: 8,
        start_date: '2023-08-22',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Introduction to Financial Management',
        description: 'Learn the basics of financial management, including budgeting, financial analysis, and investment decision-making.',
        status: 'open',
        workload: 35,
        CategoryId: 9,
        start_date: '2023-08-23',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Social Media Marketing Strategies',
        description: 'Explore effective strategies for marketing and promoting products and services on social media platforms.',
        status: 'open',
        workload: 55,
        CategoryId: 10,
        start_date: '2023-08-24',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Effective Team Leadership',
        description: 'Develop essential leadership skills and learn effective strategies to lead teams and achieve organizational goals.',
        status: 'open',
        workload: 30,
        CategoryId: 11,
        start_date: '2023-08-25',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Screenwriting Workshop',
        description: 'Unleash your creativity and learn techniques to write compelling scripts for film, television, and other media.',
        status: 'open',
        workload: 25,
        CategoryId: 12,
        start_date: '2023-08-26',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Introduction to Mechanical Engineering',
        description: 'Get an introduction to the field of mechanical engineering and explore the design and mechanics of machines and systems.',
        status: 'open',
        workload: 40,
        CategoryId: 13,
        start_date: '2023-08-27',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Renewable Energy Sources',
        description: 'Discover the potential of renewable energy sources and learn about sustainable energy solutions for a greener future.',
        status: 'open',
        workload: 50,
        CategoryId: 14,
        start_date: '2023-08-28',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        image: buffer,
        imageMimeType: "image/jpg",
        name: 'Introduction to Astronomy',
        description: 'Embark on a journey to explore the wonders of the universe and learn about the fundamentals of astronomy.',
        status: 'open',
        workload: 35,
        CategoryId: 15,
        start_date: '2023-08-29',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Courses', null, {});
  }
};
